---
title: "Sequence Analysis"
description: |
  Companion Website for the little green book
date: September 27, 2019
author:
  - name: "Marcel Raab"
    url: http://marcelraab.de
    affiliation: University of Mannheim
    affiliation_url: https://www.uni-mannheim.de
  - name: "Emanuela Struffolino"
    url: https://www.wzb.eu/en/persons/emanuela-struffolino
    affiliation: WZB Berlin
    affiliation_url: https://www.wzb.eu
# citation_url: https://sa-book.github.io/companion
# slug: raabstruffolino2019companion
bibliography: biblio.bib
output:
  distill::distill_article:
    toc: false
site: distill::distill_website
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(icon)
```

This site is intended to enhance your use of the book **Sequence Analysis** by *Marcel Raab & Emanuela Struffolino*. On this webpage we provide accompanying material illustrating how to conduct sequence analysis in `r fa_r_project(colour = "#384CB7")` using the `TraMineR` package [(Gabadinho et al. 2011)](https://doi.org/10.18637/jss.v040.i04)^[also see http://traminer.unige.ch]. 

We also provide materials for Stata, although not as exhaustive, using the user-written ados `sq` [(Brzinsky-Fay et al. 2006)](https://doi.org/10.1177%2F1536867X0600600401) and `SADI` [(Halpin 2017)](https://doi.org/10.1177%2F1536867X1701700302).    

Please note that most of the materials on this site are designed to be used in tandem with the book (which we strongly recommend to buy [once it has been published]). 



<style>
div.red { background-color:#CD0000; border-radius: 5px; padding: 20px;}
</style>
<div class = "red">
**Note:<br> This site is under construction! We kindly ask you to cite us anyway, if you use the material shared on this page.**
</div>


## Citation {.appendix}

For attribution, please cite this work as:

<!-- <style>
div.green { background-color:#8DCEA4; border-radius: 3px; padding: 10px;}
</style>
<div class = "green">
**Raab, M. & Struffolino, E. (2019). Sequence Analysis. Companion Website for the little green book. Retrieved from: https://sa-book.github.io/companion**
</div> -->

<pre class="citation-appendix short">
Raab, M. & Struffolino, E. (2019). Sequence Analysis. Companion Website for the little green book. Retrieved from: https://sa-book.github.io/companion
</pre>

<p>BibTeX citation</p>
<pre class="citation-appendix long">@misc{raabstruffolino2019companion,
  author = {Raab, Marcel and Struffolino, Emanuela},
  title = {Sequence Analysis. Companion Website for the little green book},
  url = {https://sa-book.github.io/companion},
  year = {2019}
}</pre>

## References {.appendix}

Brzinsky-Fay, C., Kohler, U., & Luniak, M. (2006). *Sequence Analysis with Stata. The Stata Journal: Promoting Communications on Statistics and Stata*, 6(4), 435–460. doi: 10.1177/1536867X0600600401

Gabadinho, A., Ritschard, G., Müller, N. S., & Studer, M. (2011). *Analyzing and Visualizing State Sequences in R with TraMineR.* Journal of Statistical Software, 40(4). doi: 10.18637/jss.v040.i04

Halpin, B. (2017). *SADI: Sequence Analysis Tools for Stata*. The Stata Journal: Promoting Communications on Statistics and Stata, 17(3), 546–572. doi: 10.1177/1536867X1701700302

