---
title: "Chapter 03"
description: |
  Comparing Sequences
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

| TOC                      | Content (click for jumping to examples)  |
|-------------------------------------|-------------------------------|
| 3.1 Outlook |  No code for this section  |
| 3.2 Dissimilarity measures to compare sequences | [Create example sequences](rChapter3-3.html) |
| 3.3 Alignment techniques |  [Optimal matching (OM)](rChapter3-3.html) |
| |  [Assign costs to the alignment operations](rChapter3-3.html) |
| |  [Alignment-based extensions of OM](rChapter3-3.html) |
| 3.4 Nonalignment techniques |  [Alternative metrics to align sequences](rChapter3-4.html) |
| 3.5 Comparing dissilarity matrices | [Mantel correlation for sequences](rChapter3-5.html) |
| 3.6 Comparing sequences of different lenght | No code for this section |
| 3.7	Beyond the standard full-sample pairwise sequence comparison | [Alternative options to compare sequences](rChapter3-7.html) |
| 3.8	Multidimensional sequence analysis | [Expansion of the alphabet](rChapter3-8.html) |
|  | [Cross-tabulation of groups identified from different dissimilarity matrices](rChapter3-8.html) |
|  | [Combine domain-specific dissimilarities](rChapter3-8.html) |
|  | [Multichannel sequence analysis](rChapter3-8.html) |


This chapter introduces techniques to compare whole sequences. Aftern having reviewed the available options, we offer a tool to compare across the dissimilarity matrices that result from the use of different dissimilarity measures. Finally, we apply what we have learned so far on computing dissimilarity between one-dimensional sequences (e.g., family biographies or individual voting behavior) to the case of multichannel sequence analysis, which allows researchers to calculate dissimilarities for multiple sets of sequences simultaneously (e.g., for employment and family trajectories or for the electoral behavior of spouses). In this section of the Companion Webpage, you will find the relevant code to obtain the results presented in the book and to reproduce the figures in colors.  
